[Logger]
# Путь до файла логов
# по умолчанию ./esm_manager.log в директории исполняемого файла
# file_path =

[Database]
# Путь до файла с базой данных
# по умолчанию ./esm_manager.db в директории исполняемого файла
# file_path =

[SSH]
# Таймаут подключения к хосту по SSH, в секундах
# по умолчанию 60
# connection_timeout =

# Порт подключения к хосту по SSH по умолчанию
# по умолчанию 22
# default_port =

# Пользователь подключения к хосту по SSH по умолчанию
# по умолчанию root
# default_username =

# Пароль подключения к хосту по SSH по умолчанию
# по умолчанию 111
# default_password =

[Installation]
# Директория с файлами для установки на кассу
# по умолчанию ./packages в директории исполняемого файла
# files_dir =

[Installation.fr_connection]
# Количество попыток ожидания подключения ФР
# по умолчанию 10
# attempts =

# Время ожидания между попытками ожидания подключения ФР, в секундах
# по умолчанию 10 секунд
# delay =

[Installation.instance_connection]
# Количество попыток ожидания подключения к экземпляру драйвера
# по умолчанию 10
# attempts =

# Время ожидания между попытками ожидания подключения к экземпляру драйвера, в секундах
# по умолчанию 10 секунд
# delay =

[Installation.mark_verification]
# Количество попыток ожидания успешной проверки кода маркировки
# по умолчанию 10
# attempts =

# Время ожидания между попытками ожидания успешной проверки кода маркировки, в секундах
# по умолчанию 10 секунд
# delay =
