---
# Создание инвенторя
all:
  children:
  # Создание кастомной группы для всех касс для гибкости инвенторя
    all_nodes:
      children:
        # Ноды и переменные на которые необходимо установить тспиот 
        tspiot_nodes:
          hosts:
            cash-1:
              ansible_host: 127.0.0.1
            cash-2:
              ansible_host: 127.0.0.2
          
          vars:
            ansible_user: root
            ansible_connection: ssh