! ***** Файл автоматически сгенерирован devicemanager ***** !

; Тип устройства: 'Денежный ящик', название: 'Подключен к ФР' (номер '1')
[Hw.cashdrawer.Fr.1]
fr = fiscalregister_1

; Тип устройства: 'Сканер', название: 'Mindeo' (номер '1')
[Hw.scanner.Mindeo.1]
transport = usbserial
device = /dev/ttyACM0    # Порт
vendor = 27dd            # Vendor ID
product = 0002           # Product ID
hub = 2-1:1.0            # Шлюз
baudrate = 9600          # Скорость
timeout = 50             # Таймаут
autoDetectionMode = true # Автоматическое обнаружение

; Тип устройства: 'ФР', название: 'PosCenter' (номер '1')
[Hw.fiscalregister.PosCenter.1]
speedEnumerate = true    # Перебор скорости
transport = tcp
host = 192.168.137.111   # Хост
port = 7778              # Порт
connecttimeout = 1000    # Таймаут
baudrate = 115200        # Скорость
protocolType = v1        # Версия протокола

; Тип устройства: 'Сканер', название: 'Базовый' (номер '0')
[Hw.scanner.Serial.0]
transport = usbserial
device = /dev/ttyUSB0    # Порт
vendor = 0c2e            # Vendor ID
product = 0720           # Product ID
hub = 2-3.4:1.0          # Шлюз
baudrate = 9600          # Скорость
timeout = 50             # Таймаут

